USE [master];
GO
BACKUP DATABASE [$(DBNAME)]
TO DISK = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER22\MSSQL\Backup\$(DBNAME).bak' 
WITH NOFORMAT, NOINIT,
NAME = N'$(DBNAME)-Full Database Backup', SKIP, NOREWIND, NOUNLOAD, STATS = 10;
GO

USE [master];
GO
RESTORE DATABASE [$(DBNAME)_CLONE] FROM  DISK = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER22\MSSQL\Backup\$(DBNAME).bak' 
WITH  FILE = 1,  MOVE N'$(DBNAME)' TO N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER22\MSSQL\DATA\$(DBNAME)_CLONE.mdf',  
MOVE N'$(DBNAME)_log' TO N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER22\MSSQL\DATA\$(DBNAME)_CLONE_log.ldf',  NOUNLOAD,  STATS = 5
GO