####################################################################
#  GitHub Action for Diff
#  database changes using Liquibase Pro.
#####################################################################
name: 'Liquibase Pro Diff'
run-name: ${{ inputs.environment}} diff by ${{ github.actor }}

on:

  workflow_dispatch:
    # Following are the inputs received via the GitHubActions Run workflow dialog
    inputs:
      # The type 'environment' will automatically pull in the environments created in GitHub
      environment:
        description: 'target environment to diff'
        type: environment
        required: true

####################################################################
#  Set up the environment
#####################################################################
env:
  # AWS S3 bucket is the host part of the S3 bucket
  AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
  
  # AWS Access credentials use by the Liquibase Pro S3 Extension
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  # Default AWS region
  AWS_REGION: us-east-1
  
  # Pro License key
  # See https://docs.liquibase.com/workflows/liquibase-pro/how-to-apply-your-liquibase-pro-license-key.html
  LIQUIBASE_LICENSE_KEY: ${{ secrets.LIQUIBASE_PRO_LICENSE_KEY }}
  
  # JDBC URL of the database per environment
  # See https://docs.liquibase.com/workflows/liquibase-community/using-jdbc-url-in-liquibase.html
  LIQUIBASE_COMMAND_URL: ${{ secrets.LIQUIBASE_URL }}

  # Credentials for the environment's database https://docs.liquibase.com/parameters/command-parameters.html
  LIQUIBASE_COMMAND_USERNAME: ${{ secrets.LIQUIBASE_USERNAME }}
  LIQUIBASE_COMMAND_PASSWORD: ${{ secrets.LIQUIBASE_PASSWORD }}
  
  # Liquibase schema: Specified to allow flexibility in storage of Liquibase Change Tracking Tables
  # See https://docs.liquibase.com/parameters/liquibase-schema-name.html
  LIQUIBASE_LIQUIBASE_SCHEMA_NAME: gh
  
  # Default schema: Specify schema for all changes
  LIQUIBASE_COMMAND_DEFAULT_SCHEMA_NAME: gh

  # Search path (See https://docs.liquibase.com/concepts/changelogs/how-liquibase-finds-files.html)
  LIQUIBASE_SEARCH_PATH: flows
  ENVIRONMENT: ${{ inputs.environment }}
  REF_ENVIRONMENT: ${{ inputs.ref_environment }}

jobs:
  #########################################################################
  #  Diff
  #########################################################################

  diff:
    runs-on: [self-hosted]
    environment: ${{ inputs.environment }}
    
    # Specify the Docker container to use for the job
    container:
      image: liquibase/liquibase:latest
      options: --user root
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Install Extensions Using LPM
      run: |
        whoami
        lpm update
        lpm add liquibase-s3-extension

    - name: Base64 decode
      uses: akiojin/decode-base64-github-action@v0.1.0
      id: decode-base64
      with:
        base64: ${{ secrets.P12_KEY_BASE64 }}
        output-path: ${{ runner.temp }}/csteambq-0df2-44cd43403fe1.p12
        
    - name: Test output
      run: |
        echo "Path=${{ steps.decode-base64.outputs.output-path }}"
        cat ${{ steps.decode-base64.outputs.output-path }}
        liquibase status --changelog-file="db.changelog-main.yaml" --url=${{ format('{0}{1}', vars.LIQUIBASE_DIFF_URL, steps.decode-base64.outputs.output-path) }} --license-key=${{ secrets.LIQUIBASE_LICENSE_KEY }}
        
      
    - name: Status
      uses: liquibase-github-actions/status@v4.28.0
      with:
        changelogFile: "db.changelog-main.yaml"
        url: ${{ format('{0}{1}', vars.LIQUIBASE_DIFF_URL, steps.decode-base64.outputs.output-path) }}
        headless: true
        licenseKey: ${{ secrets.LIQUIBASE_LICENSE_KEY }}
        logLevel: INFO

    # - name: Diff
      # uses: liquibase-github-actions/diff@v4.29.2
      # with:
        # referenceUrl: ${{ secrets.LIQUIBASE_DIFF_REF_URL }}
        # url: ${{ secrets.LIQUIBASE_DIFF_URL }}
        # headless: true
        # licenseKey: ${{ secrets.LIQUIBASE_LICENSE_KEY }}
        # logLevel: INFO