####################################################################
#  GitHub Action to connect to a db using AWS Secrets
#  Snowflake, and Liquibase Pro.
#  Environments: DEV, TEST, PROD
#####################################################################
name: 'Liquibase Pro Connect with AWS Secrets'
run-name: ${{ inputs.environment}} connect by ${{ github.actor }}

on:

  workflow_dispatch:
    # Following are the inputs received via the GitHubActions Run workflow dialog
    inputs:
      # The type 'environment' will automatically pull in the environments created in GitHub
      environment:
        description: 'Environment to connect'
        type: environment
        required: true

####################################################################
#  Set up the environment
#####################################################################
env:
  
  # AWS Access credentials use by the Liquibase Pro AWS Secrets Extension
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  # Default AWS region
  AWS_REGION: us-east-1

  # GitHub Environment
  ENVIRONMENT: ${{ inputs.environment }}
  
  # Liquibase schema: Specified to allow flexibility in storage of Liquibase Change Tracking Tables
  # See https://docs.liquibase.com/parameters/liquibase-schema-name.html
  LIQUIBASE_LIQUIBASE_SCHEMA_NAME: ${{ inputs.environment }}
  
  # Default schema: Specify schema for all changes
  LIQUIBASE_COMMAND_DEFAULT_SCHEMA_NAME: ${{ inputs.environment }}
  
  # Search path (See https://docs.liquibase.com/concepts/changelogs/how-liquibase-finds-files.html)
  LIQUIBASE_SEARCH_PATH: flows, checks, changelogs
  

jobs:
  #########################################################################
  #  Connect
  #########################################################################

  connect:
    runs-on: [self-hosted]
    environment: ${{ inputs.environment }}
    
    # Specify the Docker container to use for the job
    container:
      image: liquibase/liquibase:latest
      options: --user root
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Install Extensions Using LPM
      run: |
        lpm update
        lpm add liquibase-aws-secrets-manager
      
    - name: Connect
      uses: liquibase-github-actions/connect@v4.32.0
      with:
        url: aws-secrets,asmith_snowflake,${{ inputs.environment }}_url
        username: aws-secrets,asmith_snowflake,${{ inputs.environment }}_username
        password: aws-secrets,asmith_snowflake,${{ inputs.environment }}_password
        licenseKey: aws-secrets,asmith_snowflake,license

    - name: Flows
      uses: liquibase-github-actions/flow@v4.32.0
      with:
        flowFile: "liquibase-build.flowfile.yaml"
        url: aws-secrets,asmith_snowflake,${{ inputs.environment }}_url
        username: aws-secrets,asmith_snowflake,${{ inputs.environment }}_username
        password: aws-secrets,asmith_snowflake,${{ inputs.environment }}_password
        licenseKey: aws-secrets,asmith_snowflake,license